### ISSUE TITLE
Kindly tell how to run it on gpu,right now running on cpu

### ISSUE THREAD

**Issue by haiderasad** [Amanbhandula/AlphaPose#15]
right now it is running on cpu but i want it to run on gpu kindly tell

**Comment by haiderasad** [comment]
$ python demo.py --indir examples/demo --outdir examples/res --sp
Loading YOLO model..
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\Users\HORIZON\anaconda3\envs\alpha\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Users\HORIZON\anaconda3\envs\alpha\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\PROJECTS\AlphaPose\dataloader.py", line 323, in update
    prediction = self.det_model(img, CUDA=True)
  File "D:\Users\HORIZON\anaconda3\envs\alpha\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PROJECTS\AlphaPose\yolo\darknet.py", line 332, in forward
    x = self.module_list[i](x)
  File "D:\Users\HORIZON\anaconda3\envs\alpha\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Users\HORIZON\anaconda3\envs\alpha\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\Users\HORIZON\anaconda3\envs\alpha\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Users\HORIZON\anaconda3\envs\alpha\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED


now i am getting this

**Comment by siyuhe0120** [comment]
This project runs on GPU by default
